name: Coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn coverage
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
