name: Push build

on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn doc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply build
